In [3]:
import torch
import torch.nn.functional as F

num_nodes = 10

sparsity = 0.3

adjacency_matrix = torch.rand(num_nodes, num_nodes)
adjacency_matrix = (adjacency_matrix < sparsity).float()


adjacency_matrix = adjacency_matrix * (1 - torch.eye(num_nodes))

print("Random Adjacency Matrix:")
print(adjacency_matrix)

Random Adjacency Matrix:
tensor([[0., 1., 0., 1., 0., 0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 1., 0., 1., 1., 0.],
        [0., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
        [1., 0., 1., 1., 0., 0., 0., 0., 0., 1.],
        [1., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 1., 0., 0., 0., 0., 1.],
        [1., 0., 1., 0., 0., 1., 1., 1., 1., 0.]])


In [18]:
from model import CongestionLearnableEmbedding, CongestionWrapperEncoder
import torch
from parameters import CONGESTION_EMBEDDING_DIM

cong = torch.randint(1, 10, size=(10, num_nodes)).unsqueeze(0)
print(cong)

edge_index = torch.randint(high=num_nodes-1, size=(2, num_nodes**2//10))
print(edge_index)
x = CongestionWrapperEncoder(CongestionLearnableEmbedding, num_nodes, CONGESTION_EMBEDDING_DIM, CONGESTION_EMBEDDING_DIM, 1, 0.1)
# print(x(cong, edge_index))
print(x(cong, edge_index).shape)

tensor([[[2, 5, 1, 8, 6, 9, 5, 5, 1, 1],
         [9, 3, 7, 1, 4, 2, 2, 6, 6, 9],
         [8, 3, 2, 5, 5, 3, 5, 5, 9, 8],
         [9, 5, 9, 6, 8, 2, 6, 2, 7, 3],
         [8, 7, 5, 1, 3, 3, 3, 4, 8, 7],
         [5, 9, 3, 1, 1, 7, 5, 9, 2, 7],
         [6, 5, 1, 8, 9, 2, 5, 8, 4, 1],
         [7, 1, 6, 8, 6, 7, 9, 5, 4, 2],
         [8, 5, 2, 8, 1, 9, 7, 9, 4, 1],
         [7, 4, 2, 4, 4, 8, 6, 5, 3, 7]]])
tensor([[6, 6, 3, 5, 8, 7, 6, 1, 2, 2],
        [0, 6, 8, 2, 4, 5, 1, 3, 1, 3]])
torch.Size([1, 10, 10, 5]) input
torch.Size([10, 10, 5]) after input
10 10 squezzed
DataBatch(x=[100, 5], edge_index=[2, 100], batch=[100], ptr=[11])
torch.Size([1, 10, 50])


In [8]:
import torch
from torch_geometric.nn import GATConv


batch_size = 3
num_nodes = 10
num_features = 16

x = torch.randn(batch_size, num_nodes, num_features)

# edge_index = torch.randint(0, num_nodes, (2, num_nodes * 3))
edge_index = torch.stack([adjacency_matrix for x in range(3)])
print(edge_index)

in_channels = num_features
out_channels = 8
num_heads = 2

gat_layer = GATConv(in_channels, out_channels, heads=num_heads)

output_tensor = gat_layer(x, edge_index)

print("Shape of output_tensor:", output_tensor.shape)

tensor([[[0., 1., 0., 1., 0., 0., 0., 0., 0., 1.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 1., 0., 1., 1., 0.],
         [0., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
         [1., 0., 1., 1., 0., 0., 0., 0., 0., 1.],
         [1., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
         [0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 1., 1., 0., 1., 0., 0., 0., 0., 1.],
         [1., 0., 1., 0., 0., 1., 1., 1., 1., 0.]],

        [[0., 1., 0., 1., 0., 0., 0., 0., 0., 1.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 1., 0., 1., 1., 0.],
         [0., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
         [1., 0., 1., 1., 0., 0., 0., 0., 0., 1.],
         [1., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
         [0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 1., 1., 0., 1., 0., 0., 0., 0., 1.],
         [1., 0., 1., 0., 0.,

AssertionError: Static graphs not supported in 'GATConv'

In [ ]:
import torch
import torch.nn as nn
from torch_geometric.nn import GATConv
from torch_geometric.data import Data


edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
x = torch.rand(3, 16)  

data = Data(x=x, edge_index=edge_index)


class GraphAttentionLayer(nn.Module):
    def __init__(self, in_channels, out_channels, heads=1, dropout=0.6):
        super().__init__()
        self.gat_conv = GATConv(in_channels, out_channels, heads=heads, dropout=dropout)

    def forward(self, data):
        x = self.gat_conv(data.x, data.edge_index)
        return x


input_features = 16
output_features = 8
num_heads = 2

graph_attention_layer = GraphAttentionLayer(input_features, output_features, heads=num_heads)

output = graph_attention_layer(data)

print(output)

In [ ]:
import torch
import torch.nn as nn
from torch_geometric.nn import GATConv
from torch_geometric.data import Data

# Example: Batch of graphs with 3 graphs, each having 4 nodes and 16 features per node
batch_size = 3
num_nodes = 4
num_features = 16

edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
x = torch.rand(batch_size, num_nodes, num_features)

data = Data(x=x, edge_index=edge_index)

class GraphAttentionLayer(nn.Module):
    def __init__(self, in_channels, out_channels, heads=1, dropout=0.6):
        super().__init__()
        self.gat_conv = GATConv(in_channels, out_channels, heads=heads, dropout=dropout)

    def forward(self, data):
        x = self.gat_conv(data.x, data.edge_index)
        return x

input_features = 16
output_features = 8
num_heads = 2

graph_attention_layer = GraphAttentionLayer(input_features, output_features, heads=num_heads)

# Forward pass through the GAT layer for the entire batch
output = graph_attention_layer(data)

print(output)


In [1]:
from model import CongestionLearnableEmbedding, CongestionWrapperEncoder, CongestionModel, CongestionTransformerDecoder
import torch
from parameters import CONGESTION_EMBEDDING_DIM
num_nodes = 10
cong = torch.randint(1, 10, size=(10, num_nodes)).unsqueeze(0)
print(cong)

edge_index = torch.randint(high=num_nodes-1, size=(2, num_nodes**2//10))

# x = CongestionWrapperEncoder(CongestionLearnableEmbedding, num_nodes, CONGESTION_EMBEDDING_DIM, CONGESTION_EMBEDDING_DIM, 1, 0.1)
# print(x(cong, edge_index))
# x(cong, edge_index).shape

x = CongestionModel(CongestionLearnableEmbedding, CongestionWrapperEncoder, CongestionTransformerDecoder, None, 10, 5, 5, 1, 0.1)(cong, edge_index)
x

tensor([[[5, 3, 6, 1, 5, 7, 2, 8, 3, 6],
         [8, 9, 9, 6, 7, 4, 3, 3, 6, 5],
         [8, 6, 4, 4, 9, 2, 6, 5, 2, 6],
         [3, 7, 4, 2, 5, 2, 9, 4, 9, 4],
         [4, 5, 2, 2, 4, 4, 9, 8, 9, 7],
         [6, 8, 7, 4, 5, 1, 3, 3, 6, 4],
         [3, 6, 9, 4, 8, 6, 4, 4, 8, 8],
         [8, 1, 3, 6, 7, 6, 7, 1, 7, 4],
         [3, 3, 1, 6, 8, 6, 7, 3, 7, 1],
         [4, 4, 5, 9, 9, 2, 2, 4, 6, 4]]])


TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
